[build]
builder = "nixpacks"

[deploy]
startCommand = "flask db upgrade && gunicorn app:app -c gunicorn.conf.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
