"""initial schema

Revision ID: ca868fe1158c
Revises: 
Create Date: 2026-04-05 13:42:36.093180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca868fe1158c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('HEALTH', 'PERSONAL_GROWTH', 'RELATIONSHIPS', 'WORK', name='goalcategory'), nullable=False),
    sa.Column('priority', sa.Enum('MUST', 'SHOULD', 'COULD', 'NEED_MORE_INFO', name='goalpriority'), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('target_quarter', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'ON_HOLD', name='goalstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('WORK', name='projecttype'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'DAY_OF_WEEK', name='recurringfrequency'), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('WORK', 'PERSONAL', name='tasktype'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('tier', sa.Enum('TODAY', 'THIS_WEEK', 'BACKLOG', 'FREEZER', 'INBOX', name='tier'), nullable=False),
    sa.Column('type', sa.Enum('WORK', 'PERSONAL', name='tasktype'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('goal_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checklist', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'DELETED', name='taskstatus'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('recurring_tasks')
    op.drop_table('projects')
    op.drop_table('import_log')
    op.drop_table('goals')
    # ### end Alembic commands ###
