"""add batch_id to projects (#131 — recycle bin undo)

Revision ID: fe97b028f4d0
Revises: d8e7c6b5a4f3
Create Date: 2026-04-30 14:20:20.985967

PR66 audit fix #131. Project rows now stamp ``batch_id`` so bulk-imported
projects can be found and undone via the recycle bin (same shape as
Goal.batch_id and Task.batch_id). The autogenerated noise in the original
template (false-positive enum/varchar alter_columns on tasks +
recurring_tasks, plus indexes that already exist in production) was
pruned — those came from SQLite-vs-Postgres type detection on a local
dev database and would fail in prod. This migration is JUST the project
column + its index.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe97b028f4d0'
down_revision = 'd8e7c6b5a4f3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Uuid(), nullable=True))
        batch_op.create_index('ix_projects_batch_id', ['batch_id'], unique=False)


def downgrade():
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_batch_id')
        batch_op.drop_column('batch_id')
